---
image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  PROJECT_SOURCE_DIR: "."
  TEST_DIR: "tests"

cache: &global_cache
  key: "$CI_JOB_STAGE"
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - python -m venv venv
  - source venv/bin/activate

stages:
  #  - lint
  - test
#  - docs
#  - deploy

#lint:
#  stage: lint
#  cache:
#    <<: *global_cache
#    paths:
#      - $PRE_COMMIT_HOME
#      - .cache/pip
#      - venv/
#  script:
#    - pip install pre-commit
#    - pre-commit run --all-files

test_unit:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pytest -v $TEST_DIR

#sphinx:
#  stage: docs
#  script:
#    - pip install -r requirements.txt -r requirements-docs.txt
#    - make html -C docs
#
#docker_build:
#  stage: deploy
#  image: docker:20
#  services:
#    - docker:20-dind
#  cache: { }
#  before_script: [ ]
#  script:
#    - docker build .
